/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-12-03 09:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class follow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/day/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698885718143L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Agency - Start Bootstrap Theme</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/follow_styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t<!-- FONT -->\r\n");
      out.write("   \t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Font.css\" rel=\"stylesheet\"/>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("        \r\n");
      out.write("<!-- 부트스트랩 CSS 파일 포함 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 JavaScript 및 팝퍼 및 jQuery 포함 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("<!-- <style type=\"text/css\">\r\n");
      out.write("   .d-flex {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .rounded-circle {\r\n");
      out.write("    width: 230px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    /* padding: 40px; */ /* 간격을 조절할 수 있는 padding 속성 */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: 15px\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("/* 사용자 정의 CSS */\r\n");
      out.write(".carousel-control-prev,\r\n");
      out.write(".carousel-control-next {\r\n");
      out.write("  width: 30px; /* 원하는 너비로 변경하세요 */\r\n");
      out.write("  opacity: 1; /* 버튼 투명도를 1로 설정하여 표시됩니다 */\r\n");
      out.write("  background-color: #f8f9fa; /* 원하는 색상으로 변경하세요 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-control-prev-icon,\r\n");
      out.write(".carousel-control-next-icon {\r\n");
      out.write("  background-color: #b7b7b76b; /* 원하는 화살표 아이콘 색상으로 변경하세요 */\r\n");
      out.write("}      \r\n");
      out.write("</style> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".g-4{\r\n");
      out.write("--bs-gutter-x: 2rem !important;\r\n");
      out.write("--bs-gutter-y: 2rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   .carousel {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      /* height: 430px; */\r\n");
      out.write("      /* padding: 2em 0 2em 0; */\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("      .carousel .forward, .carousel .backward {\r\n");
      out.write("         position: absolute;\r\n");
      out.write("         top: 50%;\r\n");
      out.write("         width: 6em;\r\n");
      out.write("         height: 12em;\r\n");
      out.write("         margin-top: -6em;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("         .carousel .forward:before, .carousel .backward:before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 6em;\r\n");
      out.write("            height: 6em;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            background-color: rgb(119 100 95 / 15%);\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            margin-top: -3em;\r\n");
      out.write("            -moz-transition: background-color 0.35s ease-in-out;\r\n");
      out.write("            -webkit-transition: background-color 0.35s ease-in-out;\r\n");
      out.write("            -o-transition: background-color 0.35s ease-in-out;\r\n");
      out.write("            -ms-transition: background-color 0.35s ease-in-out;\r\n");
      out.write("            transition: background-color 0.35s ease-in-out;\r\n");
      out.write("            -webkit-backface-visibility: hidden;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel .forward:after, .carousel .backward:after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            width: 3em;\r\n");
      out.write("            height: 3em;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            margin: -1.5em 0 0 0;\r\n");
      out.write("            background: url(\"images/arrow.svg\") no-repeat center center;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel .forward:hover:before, .carousel .backward:hover:before {\r\n");
      out.write("            background-color: rgb(20 18 17 / 49%);\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      .carousel .forward {\r\n");
      out.write("         right: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("         .carousel .forward:before {\r\n");
      out.write("            right: -3em;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel .forward:after {\r\n");
      out.write("            right: -0.25em;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      .carousel .backward {\r\n");
      out.write("         left: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("         .carousel .backward:before {\r\n");
      out.write("            left: -3em;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel .backward:after {\r\n");
      out.write("            left: -0.25em;\r\n");
      out.write("            -moz-transform: scaleX(-1);\r\n");
      out.write("            -webkit-transform: scaleX(-1);\r\n");
      out.write("            -ms-transform: scaleX(-1);\r\n");
      out.write("            transform: scaleX(-1);\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      .carousel .reel {\r\n");
      out.write("         white-space: nowrap;\r\n");
      out.write("         position: relative;\r\n");
      out.write("         -webkit-overflow-scrolling: touch;\r\n");
      out.write("         /* padding: 0 2em 0 2em; */\r\n");
      out.write("      }\r\n");
      out.write("      .reel *{\r\n");
      out.write("      \tfont-family: 'SUITE-Regular'\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .carousel article {\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("         width: 20%;\r\n");
      out.write("         background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         /* padding: 0 1em 3em 1em;\r\n");
      out.write("         margin: 0 2em 0 0; */\r\n");
      out.write("         margin: 0 !important;\r\n");
      out.write("         white-space: normal;\r\n");
      out.write("         opacity: 1.0;\r\n");
      out.write("         -moz-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("         -webkit-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("         -ms-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("         transition: opacity 0.75s ease-in-out;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("         .carousel article.loading {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel article .image {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: auto;\r\n");
      out.write("            /* margin-right: -2em;\r\n");
      out.write("            margin-bottom: 3em; */\r\n");
      out.write("            margin: 0 !important;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel article a.image.featured::after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding-bottom: 56.25%;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         .carousel article a.image.featured img {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 13em;\r\n");
      out.write("            height: 13em;\r\n");
      out.write("          /* max-height: 100%; */\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         .carousel article p {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("/* 이미지 컨테이너 스타일 */\r\n");
      out.write(".carousel article a.image.featured {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* h4와 p 태그 스타일 */\r\n");
      out.write(".carousel article h4,\r\n");
      out.write(".carousel article p {\r\n");
      out.write("    margin: 0; /* 기본 마진 제거 */\r\n");
      out.write("    margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image.featured {\r\n");
      out.write("    display: block;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .reel 내부에 있는 이미지만 스타일 적용 */\r\n");
      out.write(".reel article a.image.featured img {\r\n");
      out.write("    object-fit: cover; /* 이미지를 화면에 맞게 조절 */\r\n");
      out.write("    max-height: 100%; /* 최대 높이 설정 */\r\n");
      out.write("    width: 56%; /* 가로 너비 100%로 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt-container {\r\n");
      out.write("    /* background-color: teal; */\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".col-lg-8.mx-auto.text-center {\r\n");
      out.write("    margin-top: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".follow-board {\r\n");
      out.write("    max-width: 1140px;\r\n");
      out.write("    margin: 0 auto; /* 수평 가운데 정렬을 위한 margin 설정 */\r\n");
      out.write("    margin-top: 70px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.heartImg {\r\n");
      out.write("    width: 15px;\r\n");
      out.write("    margin-right: 8px;\r\n");
      out.write("    margin-bottom: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-item-img {\r\n");
      out.write("padding-right: 0.3em;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    font-size: 11pt;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write("    /* 작은 화면에 대한 스타일 설정 */\r\n");
      out.write("@media only screen and (max-width: 991px) {\r\n");
      out.write(".carousel article {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0 !important;\r\n");
      out.write("    white-space: normal;\r\n");
      out.write("    opacity: 1.0;\r\n");
      out.write("    -moz-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("    -webkit-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("    -ms-transition: opacity 0.75s ease-in-out;\r\n");
      out.write("    transition: opacity 0.75s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#team h5, \r\n");
      out.write("#team h6 {\r\n");
      out.write("   display:inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cardTitle{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("}\r\n");
      out.write(".cardTitle:hover{\r\n");
      out.write("   text-decoration: underline;\r\n");
      out.write("   color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.card-img-top {\r\n");
      out.write("border-bottom: 1px solid #d2d2d263;\r\n");
      out.write("   height: 14rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body{\r\n");
      out.write("text-align: center;\r\n");
      out.write("   height: 7.5rem;\r\n");
      out.write("   padding: 0.8em 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".txt-container > a {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".follow-section * {\r\n");
      out.write("\tfont-family:'SUITE-Regular';\r\n");
      out.write("}\r\n");
      out.write("h4.card-title {\r\n");
      out.write("    font-size: 21px;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("p.card-title {\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: #959595;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Team-->\r\n");
      out.write("        <section class=\"page-section bg-sec follow-section\" id=\"team\" >\r\n");
      out.write("            <div class=\"container\" id=\"width-div\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_nick }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님의 FOLLOW</h2>\r\n");
      out.write("                   <!--<h3 class=\"section-subheading text-muted\">~팔로우한사람 목록입니당~</h3>-->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 이웃 목록 -->\r\n");
      out.write("        \r\n");
      out.write("               <!-- Carousel -->\r\n");
      out.write("               <section class=\"carousel\">\r\n");
      out.write("                  <div class=\"reel\">\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("               </section>                \r\n");
      out.write("      </div>\r\n");
      out.write("         </section>  \r\n");
      out.write("             <section class=\"bg-sec follow-sec\" id=\"team\" >\r\n");
      out.write("             <div class=\"container\" id=\"width-div\">\r\n");
      out.write("             <div>\r\n");
      out.write("                <div class=\"col-lg-8 mx-auto text-center\"><p class=\"large text-muted\">구독하는 이웃의 최신 스토리를 확인해보세요</p></div>\r\n");
      out.write("             </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         <!-- 이웃 최신글 -->\r\n");
      out.write("            <div>\r\n");
      out.write("              <div id=\"follow-board\" class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n");
      out.write("              \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                  \r\n");
      out.write("            </div>    <!-- .container -->\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("         <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">                  \r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                       Copyright ⓒ 2023 D.A.Y Rights Reserved.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      \r\n");
      out.write("      var pageFrm = $(\"#story\");\r\n");
      out.write("      $(\".paginate_button a\").on(\"click\", function(e){\r\n");
      out.write("         //e 현재 클릭한 a태그 요소 자체\r\n");
      out.write("         e.preventDefault(); // a태그의 href속성 작동막기\r\n");
      out.write("         var page = $(this).attr(\"href\"); //클릭한 a태그의 href의 값\r\n");
      out.write("         pageFrm.find(\"#page\").val(page);\r\n");
      out.write("         pageFrm.submit();\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("    }) \r\n");
      out.write("    \r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    getBoard();\r\n");
      out.write("    \r\n");
      out.write("    $(window).scroll(function() {\r\n");
      out.write("        if ($(window).scrollTop() + $(window).height() > $(document).height() - 50) {\r\n");
      out.write("            getBoard();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var isAllDataLoaded = false;\r\n");
      out.write("var isLoading = false; // 요청 상태를 추적하는 플래그\r\n");
      out.write("var page = 1;\r\n");
      out.write("\r\n");
      out.write("function getBoard() {\r\n");
      out.write("    if (isAllDataLoaded || isLoading) {\r\n");
      out.write("        return; // 더 이상 로드할 데이터가 없거나, 이미 요청 중이면 함수를 종료합니다.\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    isLoading = true; // 요청 시작을 표시\r\n");
      out.write("    var id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"board/followboard\",\r\n");
      out.write("        data: {\r\n");
      out.write("            \"id\": id,\r\n");
      out.write("            \"page\": page\r\n");
      out.write("        },\r\n");
      out.write("        type: \"get\",\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        success: function(data) {\r\n");
      out.write("            if (data.length === 0) {\r\n");
      out.write("                isAllDataLoaded = true;\r\n");
      out.write("                isLoading = false; // 데이터가 없으므로 요청 상태를 종료\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            makeView(data);\r\n");
      out.write("            page++;\r\n");
      out.write("            isLoading = false; // 요청 완료\r\n");
      out.write("        },\r\n");
      out.write("        error: function() {\r\n");
      out.write("            alert(\"error\");\r\n");
      out.write("            isLoading = false; // 에러 발생 시에도 요청 상태를 종료\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function makeView(data) {\r\n");
      out.write("    var listHtml = ``;\r\n");
      out.write("    data.forEach(function(obj) {\r\n");
      out.write("        listHtml += `\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/blog/${obj.user_id}\" class=\"\"><img src=\"${obj.bd_content}\" class=\"card-img-top\" alt=\"...\"></a>\r\n");
      out.write("                     <div class=\"card-body\">\r\n");
      out.write("                     <div class=\"card-item-img\"> <img class=\"heartImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${awsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/likee.png\"><span class=\"card-text\">${obj.bd_views}</span></div>\r\n");
      out.write("                       <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/blog/${obj.user_id}\" class=\"cardTitle\"><h4 class=\"card-title\">${obj.bd_title}</h4> <p  class=\"card-title\">${obj.user_nick}</p></a>\r\n");
      out.write("                      \r\n");
      out.write("                     </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>   \r\n");
      out.write("        `;\r\n");
      out.write("    });\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    $(\"#follow-board\").append(listHtml);\r\n");
      out.write("}\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("          <!-- Scripts -->\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/jquery.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/browser.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/breakpoints.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/util.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/follow_js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/follow.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/views/main/follow.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/follow.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/main/follow.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("awsPath");
      // /WEB-INF/views/main/follow.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/follow.jsp(8,0) 'https://daydayday.s3.ap-northeast-2.amazonaws.com/day'",_jsp_getExpressionFactory().createValueExpression("https://daydayday.s3.ap-northeast-2.amazonaws.com/day",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/main/follow.jsp(368,21) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/main/follow.jsp(368,21) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/follow.jsp(368,21) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <article>\r\n");
            out.write("                           <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/blog/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"image featured\">\r\n");
            out.write("                              <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.blog_profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\" class=\"rounded-circle\">\r\n");
            out.write("                           </a>\r\n");
            out.write("                           <div class=\"txt-container\">\r\n");
            out.write("                              <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/blog/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"txt featured\">\r\n");
            out.write("                                        <h4 class=\"follow_text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.user_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("                                     </a>      \r\n");
            out.write("                           </div>            \r\n");
            out.write("                        </article>\r\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
